### ISSUE TITLE
[Feature]: Ability for populate state via operations

### ISSUE THREAD

**Issue by mweichert** [ecadlabs/taqueria#591] opened 2022-04-20 16:40 UTC
### Describe the feature you would like

As a plugin author, I would like the ability to create operations that can be created by developers using Taqueria.

As an end-developer, I would like the ability to run `taq create op [operationType] [operationParams]` to create an operation.

These operations produce outputs which are stored in persistent state.

Additionally, as an end-developer, I would like to apply all operations using `taq apply`.

### Is this feature solving a problem?

An example of an operation would be an "originate" operation defined in the Taquito plugin.

An end-developer could create that operation using:
`taq create op originate increment 1`

This would produce a file called _/operations/[currentEnvironmentName]/taquito.originate.increment.mligo_:
```
```ts
export default () => ({
    id: "[HASH]",
    name: "taquito.originate.increment.tz",
    description: "Originates increment.tz",
    task: {
        name: "originate",
        contract: "increment.tz",
        storage: 1
    }
})
```

When this operation gets applied, the Taquito originate task would be executed and originate the increment.tz contract with an initial storage value of _1_.

## How to define operations

Plugin authors could define operations they would like to expose by defining them in their schema:

```ts
Plugin.create({
    tasks: [
        // Compile task defined here
        ...
    ],
    templates: [
        // Templates defined here
        ...
    ],
    operations: [
        Operation.create({
            name: "compile",
            command: "compile <filename>",
            handler: (parsedArgs) => `
                export default () => ({
                    name: "${parsedArgs.filename}",
                    description: "Compiles ${parsedArgs.filename} to Michelson",
                    task: {
                        name: "compile",
                        sourceFile: "${parsedArgs.filename}"
                    }
                })
            `
        })
    ]
})
```

Operations have access to their options/flags/parameters using ETA templates.

## How to populate persistent state

If a user were to create an instance of the compile operation above, they would execute something like this:
```
taq create op compile increment.mligo
```

This operation returns the artifact name. This would get stored in the persistent state, represented as _.taq/[currentEnvironmentName]-state.json_:
```json
{
  "ligo.compile.increment.mligo": {
    "timestamp": "1650472738",
    "outputs": {
       "artifact": "increment.tz"
    }
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment] 2022-05-16 17:28
Closing: Duplicate of #620

**Closed by hu3man** 2022-05-16 17:28 UTC
Labels: feature, triage
