### ISSUE TITLE
🚧 Dev ➾ Tests for TVsCE running on WSL

### ISSUE THREAD

**Issue by danielelisi** [ecadlabs/taqueria#1603] opened 2022-12-08 22:30 UTC
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

As we decided to momentarily drop native Windows support for Taqueria (#1602)  we want to ensure that the TVsCE on Windows works correctly when running Taqueria from WSL.

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] 
- [ ] 

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- ... 
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment] 2023-05-15 21:41
Duplicate of #1650

**Closed by mweichert** 2023-05-15 21:41 UTC
Labels: dev-task
