### ISSUE TITLE
🐛 Bug ➾ jq to update the plugins does not update the version

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1421] opened 2022-10-26 14:50 UTC
### 🚥 Status (Internal Taqueria Team Use Only)

- [x] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

I assumed that running the .jq for the upgrade of packages (on the release notes) would give me a new version of taq. But when I checked the Taq version, the script had not updated the version.

I am not sure if it should, but as a user, I was confused that I did an upgrade, but the version did not change, and I am not confident going forward.

### 🆘 Steps to Reproduce?

1. In a version 0.20.2 taqified project, run the package update .jq from the Release Notes
2. check the version of taq

### 🐘 How impactful is this bug?

🤔 Notable but managable

### ⏱️ Prevalance

If they read the doc

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

supposed to be 0.22.2 but shows v.0.20.2

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hu3man** [comment] 2022-10-26 16:57
Closing, not a bug

**Closed by hu3man** 2022-10-26 16:57 UTC
Labels: bug, triage
