### ISSUE TITLE
As an SDET, I want tests that ensure LIGO CLI commands can be run from VS Code command palette so that the team can be confident that LIGO has feature parity between TVSCE and TCLI

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#645] opened 2022-04-28 20:53 UTC
As an SDET  I want to add tests to verify that the next CLI commands can run from VS Code command palette:
- @command:taqueria.install @taqueria/plugin-ligo
- @command:taqueria.compile_ligo

**Comment by hu3man** [comment] 2022-10-18 17:46
@michaelkernaghan for context

**Comment by michaelkernaghan** [comment] 2023-01-08 03:19
dupe of #1650

**Closed by michaelkernaghan** 2023-01-08 03:19 UTC
Labels: testing, VsCE
