### ISSUE TITLE
Add automated tests for SmartPy Plugin commands for VS Code Extension

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#687] opened 2022-05-05 15:48 UTC
As an SDET, I want to add tests to verify that the next CLI commands can run from VS Code command palette:
@command:taqueria.install @taqueria/plugin-smartpy
@command:taqueria.compile_smartpy

**Comment by hu3man** [comment] 2022-10-18 17:45
@michaelkernaghan for context

**Comment by michaelkernaghan** [comment] 2023-01-08 03:19
dupe of #1650

**Closed by michaelkernaghan** 2023-01-08 03:19 UTC
Labels: testing, VsCE
