### ISSUE TITLE
TASK - E2E Testing Framework for VS Code

### ISSUE THREAD

**Issue by russellmorton** [ecadlabs/taqueria#33] opened 2021-12-09 19:08 UTC
### Description
Definition and implementation of the testing framework for the VS Code plugin.

#### Acceptance Criteria
- [ ] Testing framework finalized
- [ ] Initial testing implemented

**Comment by hu3man** [comment] 2022-10-18 17:47
@michaelkernaghan for context

**Comment by michaelkernaghan** [comment] 2023-01-08 03:19
dupe of #1650

**Closed by michaelkernaghan** 2023-01-08 03:19 UTC
Labels: testing, VsCE
