### ISSUE TITLE
Taqueria provides a task `taq update` which will update the plugins on the project

### ISSUE THREAD

**Issue by hu3man** [ecadlabs/taqueria#1547] opened 2022-11-24 18:45 UTC
### 🚥 Definition of Done

- [ ] 🎯 Planning and Design
- [ ] 🏎️ Dev Implementation Complete
- [ ] ♾️ PR Merged
- [ ] 🏆 Product Acceptance

### 🧰 Work Description

The Taqueria CLI has very tight coupling to Plugins where the versions of each must be the same. Given the fast release cycle of Taqueria, users need an early and reliable way to update the plugin versions on a project

### ⚖️ Acceptance Criteria

✨ Functional: 
- [ ] A task `taq update plugins` is exposed, which updates all installed plugins on a given 
- [ ] Taqueria CLI can check to see if the currently installed plugin versions match the CLI version and warns the user if not

### 🔭 Scope

🙅‍♂️ Out of Scope: 
- Minimum supported versions
 
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment] 2023-05-15 21:53
Duplicate of #1499

**Closed by mweichert** 2023-05-15 21:53 UTC
Labels: dev-task
