### ISSUE TITLE
🐛 Bug ➾ if I do taq compile-all and not taq compile myfile.jsligo it create infite storageList files

### ISSUE THREAD

**Issue by zamrokk** [ecadlabs/taqueria#1859] opened 2023-03-31 09:06 UTC
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

here my printscreen

![image](https://user-images.githubusercontent.com/2536368/229076692-c7ec4c8c-e9b5-4ee1-9c0a-dc2dbdc4ff1c.png)

See that every time I run the command it duplicates the file created for storage and parameter ?

### 🆘 Steps to Reproduce?

`TAQ_LIGO_IMAGE=ligolang/ligo:next taq compile-all`

I use this version containing a ligo bugfix : `npm i @taqueria/plugin-ligo@0.28.4-1852.e20decfd --registry https://npm.ecadinfra.com/ `

### 🐘 How impactful is this bug?

None

### 💻 Operating System

None

### 🕸️ System Architecture

None

### 🌮 Taqueria Version

specific look above

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment] 2023-04-06 18:24
This needs to be tested against the work in #1864

**Comment by zamrokk** [comment] 2023-04-14 13:58
on v0.28.5, taq compile-all does not work at all


![image](https://user-images.githubusercontent.com/2536368/232064983-c9a67aa9-5963-4c0f-8f10-a0900c26d3af.png)

**Comment by mweichert** [comment] 2023-04-14 14:03
@zamrokk mind attaching one or more of your contracts here that I can use to test with? Thanks!

**Comment by mweichert** [comment] 2023-05-15 20:13
I tested against v0.28.5 and was able to reproduce. The problem is fixed in v0.28.6.

**Closed by mweichert** 2023-05-15 20:13 UTC
Labels: bug, triage
