### ISSUE TITLE
[Feature]: Automated tests for template contract generation

### ISSUE THREAD

**Issue by alexzbusko** [ecadlabs/taqueria#1117] opened 2022-08-12 15:33 UTC
### Describe the feature you would like

We need automated tests for the template feature for different compiler plugins to ensure they are working as expected for template generation when changes are made. We should have tests for roughly the following:
- Help contents
- Contract creation
- Jest test creation

### Is this feature solving a problem?

This feature solves the problem of not having tests for this functionality

### Please share any additional details you have?

Details about the problem your feature solves

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mweichert** [comment] 2022-08-18 21:05
Closing as duplicate of #959

**Closed** 2022-08-23 05:16 UTC
Labels: testing
