### ISSUE TITLE
🐛 Bug ➾  Contextual help for 'taq deploy' has been broken.

### ISSUE THREAD

**Issue by michaelkernaghan** [ecadlabs/taqueria#1615] opened 2022-12-12 17:00 UTC
### 🚥 Status (Internal Taqueria Team Use Only)

- [ ] 🔬 Investigated and Verified
- [ ] ⚗️ Solution Identified and Designed 
- [ ] 🧫 Dev Implementation of Fix
- [ ] 🧪 Fix Tested and Validated
- [ ] 🏆 PR Merged

### 🆘 What happened?

It looks like the contextual help has been broken. The tests for the help files are not implemented correctly, but they do have value, and they catch the fact that contextual help is no longer being offered. In this example, it's not the text of the help that has changed, but the actual expected contextual help is not appearing. This is a bug.   This was working in previous versions but not in  'v0.27.2-alpha.'
  ● E2E Testing for taqueria taquito plugin › Verify that the taquito plugin exposes the associated options for deploy in the help menu
```
    expect(received).toBe(expected) // Object.is equality

    - Expected  - 18
    + Received  + 18

    - taq deploy <contract>
    -
    - Deploy a smart contract to a particular environment
    -
    - Options:
    -       --version     Show version number                                [boolean]
    -       --build       Display build information about the current version[boolean]
    -   -p, --projectDir  Path to your project directory               [default: "./"]
    -   -e, --env         Specify an environment configuration
    -   -y, --yes         Select "yes" to any prompt        [boolean] [default: false]
    -       --help        Show help                                          [boolean]
    -       --alias       Alias used to refer to the deployed contract's address
    -       --storage     Name of the storage file that contains the storage value as
    -                     a Michelson expression, in the artifacts directory, used for
    -                      originating a contract
    -       --sender      Name of an instantiated account to use as the sender of the
    -                     originate operation
    -       --mutez       Amount of Mutez to transfer
    + taq [command]
    +
    + Commands:
    +   taq init [projectDir]                     Initialize a new project
    +   taq opt-in                                Opt-in to sharing anonymous usage an
    +                                             alytics
    +   taq opt-out                               Opt-out of sharing anonymous usage a
    +                                             nalytics
    +   taq scaffold [scaffoldUrl] [scaffoldProj  Generate a new project using pre-mad
    +   ectDir]                                   e scaffold
    +
    + Options:
    +       --version     Show version number                                [boolean]
    +       --build       Display build information about the current version[boolean]
    +   -p, --projectDir  Path to your project directory               [default: "./"]
    +   -e, --env         Specify an environment configuration
    +
    + Taqueria is currently in BETA. You've been warned. :)
```

### 🆘 Steps to Reproduce?

1. taq init foo
2. cd foo
3. taq deploy --help --projectDir=./foo
4. there should be contextual help about how to deploy a smart contract, but there is only the generic help
5. should see "taq deploy <contract>"  but only ever see."taq [commands]"

### 🐘 How impactful is this bug?

🤯 Major disruption

### ⏱️ Prevalance

everytime

### 💻 Operating System

Windows -> Linux VM

### 🕸️ System Architecture

x64

### 🌮 Taqueria Version

v0.27.2-alpha

### 🌿 Node.js Version

v16.13.1

### ☎️ Contact Details

michaelkernaghan@ecadlabs.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by michaelkernaghan** [comment] 2022-12-12 17:52
This is fixed in a recent branch, and I will close this when I see the fix is merged into the code base.

**Comment by jevonearth** [comment] 2023-01-03 18:21
Closing this in favour of #1635.
Duplicate of #1635

**Closed by jevonearth** 2023-01-03 18:21 UTC
Labels: bug, triage
