### ISSUE TITLE
Add automated tests for Taquito Plugin commands for VS Code Extension

### ISSUE THREAD

**Issue by sinapsist** [ecadlabs/taqueria#688] opened 2022-05-05 15:49 UTC
As an SDET, I want to add tests to verify that the next CLI commands can run from VS Code command palette:
@command:taqueria.install @taqueria/plugin-taquito
@command:taqueria.deploy

**Comment by hu3man** [comment] 2022-10-18 17:45
@michaelkernaghan for context

**Comment by michaelkernaghan** [comment] 2023-01-08 03:18
dupe of #1650

**Closed by michaelkernaghan** 2023-01-08 03:18 UTC
Labels: testing, VsCE
